### ISSUE TITLE
Wrong IP used for docker container after automatic restart

### ISSUE THREAD

**Issue by arhughes** [dokku/dokku#2602]
Description of problem:
I am hosting a simple node.js application set to restart always, and when an error occurs and the application is restarted the docker container has a different IP but the nginx config is not updated to the new IP address.

For example my application crashed last night and was restarted, but is not accessible. The IP address of the docker container (using the container id in `CONTAINER.web.1`) shows that the IP address is 172.17.0.2, but the `IP.web.1` and `nginx.config` files both say 172.17.0.3.

Restarting the app with `dokku ps:restart` seems to fix the problem. When I restart it via the command line the `IP.web.1` and `nginx.config` files are both updated with the containers new IP address.

Output of the following commands

- `uname -a`:
```
Linux dokku-512mb-nyc3-01 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```

- `free -m`:
```
              total        used        free      shared  buff/cache   available
Mem:            488         104          13           6         370         341
Swap:             0           0           0
```
- `docker version`:
```
Client:
 Version:      1.13.0
 API version:  1.25
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64

Server:
 Version:      1.13.0
 API version:  1.25 (minimum version 1.12)
 Go version:   go1.7.3
 Git commit:   49bf474
 Built:        Tue Jan 17 09:58:26 2017
 OS/Arch:      linux/amd64
 Experimental: false
```

- `docker -D info`:
```
Containers: 7
 Running: 1
 Paused: 0
 Stopped: 6
Images: 22
Server Version: 1.13.0
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 39
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins:
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 03e5862ec0d8d3b3f750e19fca3ee367e13c090e
runc version: 2f7393a47307a16f8cee44a37b262e8b81021e3e
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-62-generic
Operating System: Ubuntu 16.04.1 LTS
OSType: linux
Architecture: x86_64
CPUs: 1
Total Memory: 488.4 MiB
Name: dokku-512mb-nyc3-01
ID: T4N6:UWEZ:TRD3:YXDX:2P4S:HOOR:XWSK:CJL7:WIBX:HIEH:TZIG:VVUT
Docker Root Dir: /var/lib/docker
Debug Mode (client): true
Debug Mode (server): false
Registry: https://index.docker.io/v1/
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
```

- `sigil -v`: `0.4.0`
- `docker run -ti gliderlabs/herokuish:latest herokuish version`:
```
herokuish: 0.3.24
buildpacks:
  heroku-buildpack-multi     v1.0.0
  heroku-buildpack-ruby      v150
  heroku-buildpack-nodejs    v93
  heroku-buildpack-clojure   v75
  heroku-buildpack-python    v97
  heroku-buildpack-java      v48
  heroku-buildpack-gradle    v19
  heroku-buildpack-grails    v21
  heroku-buildpack-scala     v72
  heroku-buildpack-play      v26
  heroku-buildpack-php       v117
  heroku-buildpack-go        v54
  heroku-buildpack-erlang    fa17af9
  buildpack-nginx            v8
```

- `dokku version`: `0.8.0`
- `dokku plugin`:
```
  00_dokku-standard    0.8.0 enabled    dokku core standard plugin
  20_events            0.8.0 enabled    dokku core events logging plugin
  apps                 0.8.0 enabled    dokku core apps plugin
  build-env            0.8.0 enabled    dokku core build-env plugin
  certs                0.8.0 enabled    dokku core certificate management plugin
  checks               0.8.0 enabled    dokku core checks plugin
  common               0.8.0 enabled    dokku core common plugin
  config               0.8.0 enabled    dokku core config plugin
  docker-options       0.8.0 enabled    dokku core docker-options plugin
  domains              0.8.0 enabled    dokku core domains plugin
  enter                0.8.0 enabled    dokku core enter plugin
  git                  0.8.0 enabled    dokku core git plugin
  logs                 0.8.0 enabled    dokku core logs plugin
  named-containers     0.8.0 enabled    dokku core named containers plugin
  nginx-vhosts         0.8.0 enabled    dokku core nginx-vhosts plugin
  plugin               0.8.0 enabled    dokku core plugin plugin
  proxy                0.8.0 enabled    dokku core proxy plugin
  ps                   0.8.0 enabled    dokku core ps plugin
  repo                 0.8.0 enabled    dokku core repo plugin
  shell                0.8.0 enabled    dokku core shell plugin
  ssh-keys             0.8.0 enabled    dokku core ssh-keys plugin
  storage              0.8.0 enabled    dokku core storage plugin
  tags                 0.8.0 enabled    dokku core tags plugin
  tar                  0.8.0 enabled    dokku core tar plugin
```

- `docker inspect CONTAINER_ID` (if applicable):
```[
    {
        "Id": "87c0f0fa2f024c6e7cbe99978eca8749e598ff136ae3451e34a15ee32e39cb40",
        "Created": "2017-02-10T03:07:59.420473235Z",
        "Path": "/start",
        "Args": [
            "web"
        ],
        "State": {
            "Status": "running",
            "Running": true,
            "Paused": false,
            "Restarting": false,
            "OOMKilled": false,
            "Dead": false,
            "Pid": 12881,
            "ExitCode": 0,
            "Error": "",
            "StartedAt": "2017-02-10T13:48:58.778275149Z",
            "FinishedAt": "2017-02-10T13:48:58.384820229Z"
        },
        "Image": "sha256:af9c4cf30cda7b4fd155f8df31973e70c763a01636407b96a5b55cb1af51f225",
        "ResolvConfPath": "/var/lib/docker/containers/87c0f0fa2f024c6e7cbe99978eca8749e598ff136ae3451e34a15ee32e39cb40/resolv.conf",
        "HostnamePath": "/var/lib/docker/containers/87c0f0fa2f024c6e7cbe99978eca8749e598ff136ae3451e34a15ee32e39cb40/hostname",
        "HostsPath": "/var/lib/docker/containers/87c0f0fa2f024c6e7cbe99978eca8749e598ff136ae3451e34a15ee32e39cb40/hosts",
        "LogPath": "/var/lib/docker/containers/87c0f0fa2f024c6e7cbe99978eca8749e598ff136ae3451e34a15ee32e39cb40/87c0f0fa2f024c6e7cbe99978eca8749e598ff136ae3451e34a15ee32e39cb40-json.log",
        "Name": "/shackapi.web.1",
        "RestartCount": 3,
        "Driver": "aufs",
        "MountLabel": "",
        "ProcessLabel": "",
        "AppArmorProfile": "",
        "ExecIDs": null,
        "HostConfig": {
            "Binds": null,
            "ContainerIDFile": "",
            "LogConfig": {
                "Type": "json-file",
                "Config": {}
            },
            "NetworkMode": "default",
            "PortBindings": {},
            "RestartPolicy": {
                "Name": "on-failure",
                "MaximumRetryCount": 10
            },
            "AutoRemove": false,
            "VolumeDriver": "",
            "VolumesFrom": null,
            "CapAdd": null,
            "CapDrop": null,
            "Dns": [],
            "DnsOptions": [],
            "DnsSearch": [],
            "ExtraHosts": null,
            "GroupAdd": null,
            "IpcMode": "",
            "Cgroup": "",
            "Links": null,
            "OomScoreAdj": 0,
            "PidMode": "",
            "Privileged": false,
            "PublishAllPorts": false,
            "ReadonlyRootfs": false,
            "SecurityOpt": null,
            "UTSMode": "",
            "UsernsMode": "",
            "ShmSize": 67108864,
            "Runtime": "runc",
            "ConsoleSize": [
                0,
                0
            ],
            "Isolation": "",
            "CpuShares": 0,
            "Memory": 0,
            "NanoCpus": 0,
            "CgroupParent": "",
            "BlkioWeight": 0,
            "BlkioWeightDevice": null,
            "BlkioDeviceReadBps": null,
            "BlkioDeviceWriteBps": null,
            "BlkioDeviceReadIOps": null,
            "BlkioDeviceWriteIOps": null,
            "CpuPeriod": 0,
            "CpuQuota": 0,
            "CpuRealtimePeriod": 0,
            "CpuRealtimeRuntime": 0,
            "CpusetCpus": "",
            "CpusetMems": "",
            "Devices": [],
            "DiskQuota": 0,
            "KernelMemory": 0,
            "MemoryReservation": 0,
            "MemorySwap": 0,
            "MemorySwappiness": -1,
            "OomKillDisable": false,
            "PidsLimit": 0,
            "Ulimits": null,
            "CpuCount": 0,
            "CpuPercent": 0,
            "IOMaximumIOps": 0,
            "IOMaximumBandwidth": 0
        },
        "GraphDriver": {
            "Name": "aufs",
            "Data": null
        },
        "Mounts": [],
        "Config": {
            "Hostname": "87c0f0fa2f02",
            "Domainname": "",
            "User": "",
            "AttachStdin": false,
            "AttachStdout": false,
            "AttachStderr": false,
            "Tty": false,
            "OpenStdin": false,
            "StdinOnce": false,
            "Env": [
                "PORT=5000",
                "USER=herokuishuser",
                "DYNO=web.1",
                "CACHE_PATH=/cache",
                "PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
            ],
            "Cmd": [
                "/start",
                "web"
            ],
            "Image": "dokku/shackapi:latest",
            "Volumes": null,
            "WorkingDir": "",
            "Entrypoint": null,
            "OnBuild": null,
            "Labels": {
                "dokku": ""
            }
        },
        "NetworkSettings": {
            "Bridge": "",
            "SandboxID": "e1d8b59685521828bc1303cea9f2acc38f1e8b8174073ace945c43c25ef724f4",
            "HairpinMode": false,
            "LinkLocalIPv6Address": "",
            "LinkLocalIPv6PrefixLen": 0,
            "Ports": {},
            "SandboxKey": "/var/run/docker/netns/e1d8b5968552",
            "SecondaryIPAddresses": null,
            "SecondaryIPv6Addresses": null,
            "EndpointID": "2bf5d28f45fa4a851d8c9b1511cde0a4d3ce393684b36d411ccc4c3789ab997d",
            "Gateway": "172.17.0.1",
            "GlobalIPv6Address": "",
            "GlobalIPv6PrefixLen": 0,
            "IPAddress": "172.17.0.2",
            "IPPrefixLen": 16,
            "IPv6Gateway": "",
            "MacAddress": "02:42:ac:11:00:02",
            "Networks": {
                "bridge": {
                    "IPAMConfig": null,
                    "Links": null,
                    "Aliases": null,
                    "NetworkID": "3400cee55722bd380e782f9520fd7305264128dfb1068ea7af8a25473c066aa8",
                    "EndpointID": "2bf5d28f45fa4a851d8c9b1511cde0a4d3ce393684b36d411ccc4c3789ab997d",
                    "Gateway": "172.17.0.1",
                    "IPAddress": "172.17.0.2",
                    "IPPrefixLen": 16,
                    "IPv6Gateway": "",
                    "GlobalIPv6Address": "",
                    "GlobalIPv6PrefixLen": 0,
                    "MacAddress": "02:42:ac:11:00:02"
                }
            }
        }
    }
]
```

- `cat /home/dokku/<app>/nginx.conf` (if applicable):
```
server {
  listen      [::]:80;
  listen      80;
  server_name shackapi.hughes.cc;
  access_log  /var/log/nginx/shackapi-access.log;
  error_log   /var/log/nginx/shackapi-error.log;

  location    / {

    gzip on;
    gzip_min_length  1100;
    gzip_buffers  4 32k;
    gzip_types    text/css text/javascript text/xml text/plain text/x-component application/javascript application/x-javascript application/json application/xml  application/rss+xml font/truetype application/x-font-ttf font/opentype application/vnd.ms-fontobject image/svg+xml;
    gzip_vary on;
    gzip_comp_level  6;

    proxy_pass  http://shackapi-5000;
    proxy_http_version 1.1;
    proxy_set_header Upgrade $http_upgrade;
    proxy_set_header Connection "upgrade";
    proxy_set_header Host $http_host;
    proxy_set_header X-Forwarded-Proto $scheme;
    proxy_set_header X-Forwarded-For $remote_addr;
    proxy_set_header X-Forwarded-Port $server_port;
    proxy_set_header X-Request-Start $msec;
  }
  include /home/dokku/shackapi/nginx.conf.d/*.conf;

}

upstream shackapi-5000 {

  server 172.17.0.3:5000;
}
```

- Link to the exact repository being deployed (if possible/applicable): https://github.com/arhughes/droidchatty/tree/winchatty

Environment details (AWS, VirtualBox, physical, etc.): DigitalOcean droplet

How was Dokku installed?: Using DigitalOcean's one click droplet deploy.

How reproducible: Has happened at least twice with the linked repository. When I tried to reproduce by writing a simple app that just forced a crash I could not get it to reproduce.

Steps to Reproduce:
1. Launch app
2. Wait for app to crash
3. Wait for dokku to automatically restart

Actual Results:
Nginx config uses wrong IP address.

Expected Results:
Nginx config uses correct IP address.

**Comment by josegonzalez** [comment]
Yeah, this is a docker issue. They sometimes - it's not clear when - change the IP of an existing container on boot. #2403 should fix the issue, so closing this one.

**Comment by bakketun** [comment]
The IP address of a docker container is not fixed. It can change whenever a container restarted. Here is a docker issue discussing this: https://github.com/docker/docker/issues/2801. The solution was to add an option to docker to specify a fixed ip (--ip and --ip6), but dokku doesn't use this option.

We experienced this bug after reboot of a dokku server. The server is running several apps any many of the apps had IP mismatch between nginx and docker. We also has a test dokku server with similar setup and apps. Reboot of this server also resulted in IP mismatch. As a workaround we added some commands to update the IP in nginx config in /etc/init/dokku-redeploy.conf
```
script
  rm /home/dokku/*/nginx.conf
  service nginx reload
  sleep 2 # give docker some time
  sudo -i -u dokku /usr/bin/dokku ps:restore
  for app in $(/usr/bin/dokku apps | tail -n +2) ; do
    /usr/bin/docker inspect --format='{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' $(cat /home/dokku/$app/CONTAINER.web.1) | (sudo -i -u dokku tee /home/dokku/$app/IP.web.1)
    sudo -i -u dokku /usr/bin/dokku nginx:build-config $app
  done
end script
```

This is not a full solution though, since docker containers can also switch IP when automatically restated due to application crash. We was also able to reproduce this by killing all apps "killall -9 sbcl" (all our apps has proccess name sbcl).

**Comment by josegonzalez** [comment]
I'm well aware of the fact that it's not fixed. It used to be, and now is not. I'm quite familiar with the problem, and working on the issue I mentioned should fix this issue.

**Comment by arhughes** [comment]
@josegonzalez what confused me is that when restarting the app using `dokku ps:restart shackapi` it picks up the new IP address from the docker container with no problem, but when the container is auto-restarted due to the process crashing it does not. I assumed that the auto-restart mechanism was essentially the same as calling `ps:restart`, but it seems that it is not.

**Comment by josegonzalez** [comment]
The restart policies just use docker restart policies, and as far as *I'm* aware, those definitely used to save the IP address.

Regardless, we'd still need to implement the networking changes from that RFC to solve this issue in any meaningful way.

**Comment by gaston23** [comment]
+1 Any updates on this? This is happening to us after each push, is this the same? We have IP mismatch between container and nginx. The workaround is ```ps:restart``` to get the correct IP.

**Comment by josegonzalez** [comment]
A few things:

- If there was an update, it would be posted.
- Follow along on #2403 for any implementation changes.
- A push is more or less equivalent to `ps:restart`, so it sounds like you're having a different issue. Please find us on [slack/irc](http://dokku.viewdocs.io/dokku/getting-started/where-to-get-help/#the-irc-and-slack-channels) so we can further investigate.

**Comment by josegonzalez** [comment]
For anyone wondering what @gaston23's issue was, it was unrelated to this. He set his proxy type via `dokku proxy:set` to `http`. This resulted in nginx not being triggered, and therefore none of the configuration was being updated.
