### ISSUE TITLE
Can't bootstrap an app because domain ftp.csx.cam.ac.uk is not reachable

### ISSUE THREAD

**Issue by alvatar** [dokku/dokku#3653]
## Description of problem

Can't bootstrap an app in a new Dokku because domain ftp.csx.cam.ac.uk is not reachable. This domain seems to be used to download the PCRE package.

### How reproducible

Always.

### Steps to Reproduce

1. Create a digital ocean dokku instance. You can update it to the latest dokku manually or not, doesn't change the outcome.
2. Configure with virtual host
3. push a repo

#### Actual Results

Timesout trying to reach ftp.csx.cam.ac.uk

#### Expected Results

Should work

## Environment Information

It's an ubunut environment, but 

### `dokku report APP_NAME` output

N/A

**Comment by josegonzalez** [comment]
This is fixed in the latest nginx buildpack. Please upgrade your herokuish version - `sudo apt update && sudo apt install herokuish` to receive the fix.

**Comment by alvatar** [comment]
Great, thank you @josegonzalez !

**Comment by alvatar** [comment]
@josegonzalez this doesn't seem to fix it. I've updated, and ensured it was indeed updated. Restarted the instance as well.
Are you sure the latest version of herokuish is available in the ubuntu repos?

**Comment by josegonzalez** [comment]
I am sure, I released it yesterday.

What is the output of:

```
dokku report
```

**Comment by alvatar** [comment]
Here:

```
-----> uname: Linux castrocastilla 4.15.0-58-generic #64-Ubuntu SMP Tue Aug 6 11:12:41 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
-----> memory:
                     total        used        free      shared  buff/cache   available
       Mem:            985         153         350           0         481         691
       Swap:             0           0           0
-----> docker version:
       Client:
        Version:           18.09.6
        API version:       1.39
        Go version:        go1.10.8
        Git commit:        481bc77
        Built:             Sat May  4 02:35:57 2019
        OS/Arch:           linux/amd64
        Experimental:      false

       Server: Docker Engine - Community
        Engine:
         Version:          18.09.6
         API version:      1.39 (minimum version 1.12)
         Go version:       go1.10.8
         Git commit:       481bc77
         Built:            Sat May  4 01:59:36 2019
         OS/Arch:          linux/amd64
         Experimental:     false
-----> docker daemon info:
       Containers: 8
        Running: 0
        Paused: 0
        Stopped: 8
       Images: 9
       Server Version: 18.09.6
       Storage Driver: overlay2
        Backing Filesystem: extfs
        Supports d_type: true
        Native Overlay Diff: true
       Logging Driver: json-file
       Cgroup Driver: cgroupfs
       Plugins:
        Volume: local
        Network: bridge host macvlan null overlay
        Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
       Swarm: inactive
       Runtimes: runc
       Default Runtime: runc
       Init Binary: docker-init
       containerd version: bb71b10fd8f58240ca47fbb579b9d1028eea7c84
       runc version: 2b18fe1d885ee5083ef9f0838fee39b62d653e30
       init version: fec3683
       Security Options:
        apparmor
        seccomp
         Profile: default
       Kernel Version: 4.15.0-58-generic
       Operating System: Ubuntu 18.04.2 LTS
       OSType: linux
       Architecture: x86_64
       CPUs: 1
       Total Memory: 985.5MiB
       Name: castrocastilla
       ID: HIZF:J54V:JZDU:RBLQ:3BBN:OUUL:ER6E:7SVT:XCWL:KYTQ:L5L7:CE7B
       Docker Root Dir: /var/lib/docker
       Debug Mode (client): true
       Debug Mode (server): false
       Registry: https://index.docker.io/v1/
       Labels:
       Experimental: false
       Insecure Registries:
        127.0.0.0/8
       Live Restore Enabled: false
       Product License: Community Engine
-----> sigil version: 0.4.0
-----> herokuish version:
       herokuish: 0.5.3
       buildpacks:
         heroku-buildpack-multi     v1.0.0
         heroku-buildpack-ruby      v201
         heroku-buildpack-nodejs    v161
         heroku-buildpack-clojure   v84
         heroku-buildpack-python    v154
         heroku-buildpack-java      v63
         heroku-buildpack-gradle    v30
         heroku-buildpack-scala     v85
         heroku-buildpack-play      v26
         heroku-buildpack-php       v159
         heroku-buildpack-go        v126
         buildpack-nginx            v12
-----> dokku version: dokku version 0.18.2
-----> dokku plugins:
       plugn: 0.3.2
         00_dokku-standard    0.18.2 enabled    dokku core standard plugin
         20_events            0.18.2 enabled    dokku core events logging plugin
         app-json             0.18.2 enabled    dokku core app-json plugin
         apps                 0.18.2 enabled    dokku core apps plugin
         builder-dockerfile   0.18.2 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.18.2 enabled    dokku core builder-herokuish plugin
         buildpacks           0.18.2 enabled    dokku core buildpacks plugin
         certs                0.18.2 enabled    dokku core certificate management plugin
         checks               0.18.2 enabled    dokku core checks plugin
         common               0.18.2 enabled    dokku core common plugin
         config               0.18.2 enabled    dokku core config plugin
         docker-options       0.18.2 enabled    dokku core docker-options plugin
         domains              0.18.2 enabled    dokku core domains plugin
         enter                0.18.2 enabled    dokku core enter plugin
         git                  0.18.2 enabled    dokku core git plugin
         logs                 0.18.2 enabled    dokku core logs plugin
         network              0.18.2 enabled    dokku core network plugin
         nginx-vhosts         0.18.2 enabled    dokku core nginx-vhosts plugin
         plugin               0.18.2 enabled    dokku core plugin plugin
         proxy                0.18.2 enabled    dokku core proxy plugin
         ps                   0.18.2 enabled    dokku core ps plugin
         repo                 0.18.2 enabled    dokku core repo plugin
         resource             0.18.2 enabled    dokku core resource plugin
         scheduler-docker-local 0.18.2 enabled    dokku core scheduler-docker-local plugin
         shell                0.18.2 enabled    dokku core shell plugin
         ssh-keys             0.18.2 enabled    dokku core ssh-keys plugin
         storage              0.18.2 enabled    dokku core storage plugin
         tags                 0.18.2 enabled    dokku core tags plugin
         tar                  0.18.2 enabled    dokku core tar plugin
         trace                0.18.2 enabled    dokku core trace plugin
```

**Comment by josegonzalez** [comment]
Do you have a `.buildpacks` file in your repository, and if so, what are the contents?

**Comment by alvatar** [comment]
No, since I'm trying to deploy just simple static apps.

**Comment by josegonzalez** [comment]
Okay well it says you have the v12 nginx buildpack there, and the v12 nginx buildpack [doesn't call that url anymore](https://github.com/dokku/buildpack-nginx/pull/38/files), so you'll need to join us on slack to resolve this.
