### ISSUE TITLE
ftp.pcre.org has been TAKEN DOWN

### ISSUE THREAD

**Issue by qs5779** [dokku/dokku#4929]
dokku version 0.26.6

## Description of problem
According to http://pcre.org/ site  ftp.pcre.org has been TAKEN DOWN

me@xxx $ git push dokku main:master
### How reproducible
100% 

### Steps to Reproduce
push a static site
me@xxx $ git push dokku main:master

#### Actual Results
Enumerating objects: 34, done.
Counting objects: 100% (34/34), done.
Delta compression using up to 8 threads
Compressing objects: 100% (32/32), done.
Writing objects: 100% (34/34), 727.79 KiB | 25.99 MiB/s, done.
Total 34 (delta 0), reused 0 (delta 0), pack-reused 0
-----> Cleaning up...
-----> Building quiensabe from herokuish
-----> Adding BUILD_ENV to build environment...
       BUILD_ENV added successfully
-----> .static app detected
-----> Copy static files to www
-----> Download and unzip pcre 8.43 via http
remote: curl: (28) Failed to connect to ftp.pcre.org port 443: Connection timed out
remote: 2021/11/15 23:24:22 exit status 28
To<redacted>:quiensabe
 ! [remote rejected] main -> master (pre-receive hook declined)
error: failed to push some refs to '<redacted>:quiensabe'

**Comment by josegonzalez** [comment]
Two things:

- This was fixed in a recent release of herokuish. You'll want to update that package.
- Please always include all the information we ask for the in the issue template.

**Comment by josegonzalez** [comment]
Note: I'm _guessing_ you're on some flavor of Ubuntu, and if its new enough (can't tell since you didn't add all the info asked for in the issue template), you can update via the following commands:

```
sudo apt-get update
sudo apt-get install dokku-update herokuish
```

In the future, you can then use `sudo dokku-update run` to update things.

**Comment by qs5779** [comment]
Thanks, I will try to be a better citizen. I did find the issue was fixed and came back here to close/update my issue. Your suggestions are very helpful.

**Comment by qs5779** [comment]
It took me a while (okay I only started evaluating dokku yesterday), but this is what I needed to set the latest from git build pack version for my static file app.  "dokku buildpacks:set <appname> https://github.com/dokku/heroku-buildpack-nginx" found at: https://dokku.com/docs/deployment/builders/herokuish-buildpacks/

**Comment by jamiehs** [comment]
This still appears to be an issue for me. What should I do if I upgraded herokuish & dokku (using the instructions from @josegonzalez) and I'm still seeing this error when trying to deploy a static site?

```
$ dokku -v
dokku version 0.26.6
```

```
...
-----> Adding BUILD_ENV to build environment...
       BUILD_ENV added successfully
-----> .static app detected
-----> Copy static files to www
-----> Download and unzip pcre 8.43 via http
curl: (28) Failed to connect to ftp.pcre.org port 443: Connection timed out
2021/11/18 21:04:09 exit status 28
2021/11/18 21:04:10 exit status 1
2021/11/18 21:04:12 exit status 1
...
```

**Comment by josegonzalez** [comment]
Do you have a `.buildpacks` file or did you manually set the buildpack somewhere?

Actually, I'm going to close this ticket. The fix was confirmed in another ticket by someone, so I would prefer folks file a ticket with all the debugging information I ask for rather than snippets of things they think might be useful.

**Comment by josegonzalez** [comment]
Please file a new ticket if you are having this issue, and include all the debugging information asked for in the issue template.
