### ISSUE TITLE
nginx.conf.sigil is not used after v0.29.0

### ISSUE THREAD

**Issue by tribela** [dokku/dokku#5518]
### Description of problem

I use `dokku git:from-image` to deploy my application and that docker image contains `/nginx.conf.sigil`
But after upgrade to v0.29.0, it is not used to generate nginx.conf

The documentation says "The nginx.conf.sigil is now extracted when source code is extracted for a build and not from the built image." and I just don't know what to do on git:from-image deployment

Also, `dokku nginx:set --global nginx-conf-sigil-path dokku/nginx.conf.sigil` command does not working as descibed

https://dokku.com/docs/appendices/0.29.0-migration-guide/?h=nginx.conf.sigil
https://dokku.com/docs/networking/proxies/nginx/#customizing-the-nginx-configuration

### Steps to reproduce

1. deploy using `git:from-image`
2. nginx.conf.sigil is contained in an image and not used for generate nginx.conf

### dokku report $APP_NAME

```
-----> uname: Linux qdon 5.4.0-132-generic #148-Ubuntu SMP Mon Oct 17 16:02:06 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux
-----> memory: 
                     total        used        free      shared  buff/cache   available
       Mem:           7957        3336        1379          23        3241        4374
       Swap:          2047          37        2010
-----> docker version: 
       Client: Docker Engine - Community
        Version:           20.10.21
        API version:       1.41
        Go version:        go1.18.7
        Git commit:        baeda1f
        Built:             Tue Oct 25 18:02:21 2022
        OS/Arch:           linux/amd64
        Context:           default
        Experimental:      true
       
       Server: Docker Engine - Community
        Engine:
         Version:          20.10.21
         API version:      1.41 (minimum version 1.12)
         Go version:       go1.18.7
         Git commit:       3056208
         Built:            Tue Oct 25 18:00:04 2022
         OS/Arch:          linux/amd64
         Experimental:     true
        containerd:
         Version:          1.6.12
         GitCommit:        a05d175400b1145e5e6a735a6710579d181e7fb0
        runc:
         Version:          1.1.4
         GitCommit:        v1.1.4-0-g5fd4c4d
        docker-init:
         Version:          0.19.0
         GitCommit:        de40ad0
-----> docker daemon info: 
       Client:
        Context:    default
        Debug Mode: true
        Plugins:
         app: Docker App (Docker Inc., v0.9.1-beta3)
         buildx: Docker Buildx (Docker Inc., v0.9.1-docker)
         compose: Docker Compose (Docker Inc., v2.12.2)
         scan: Docker Scan (Docker Inc., v0.21.0)
       
       Server:
        Containers: 8
         Running: 8
         Paused: 0
         Stopped: 0
        Images: 62
        Server Version: 20.10.21
        Storage Driver: overlay2
         Backing Filesystem: extfs
         Supports d_type: true
         Native Overlay Diff: true
         userxattr: false
        Logging Driver: json-file
        Cgroup Driver: cgroupfs
        Cgroup Version: 1
        Plugins:
WARNING: No swap limit support
         Volume: local
         Network: bridge host ipvlan macvlan null overlay
         Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
        Swarm: inactive
        Runtimes: io.containerd.runc.v2 io.containerd.runtime.v1.linux runc
        Default Runtime: runc
        Init Binary: docker-init
        containerd version: a05d175400b1145e5e6a735a6710579d181e7fb0
        runc version: v1.1.4-0-g5fd4c4d
        init version: de40ad0
        Security Options:
         apparmor
         seccomp
          Profile: default
        Kernel Version: 5.4.0-132-generic
        Operating System: Ubuntu 20.04.5 LTS
        OSType: linux
        Architecture: x86_64
        CPUs: 4
        Total Memory: 7.771GiB
        Name: qdon
        ID: BPV5:HPVF:WO3V:V2YU:UQVG:BJZ2:HKPY:HQXJ:U3TM:VQV3:2YDG:STJC
        Docker Root Dir: /var/lib/docker
        Debug Mode: false
        Registry: https://index.docker.io/v1/
        Labels:
        Experimental: true
        Insecure Registries:
         127.0.0.0/8
        Live Restore Enabled: false
       
-----> git version: git version 2.25.1
-----> sigil version: 0.9.0build+bc921b7
-----> herokuish version: 
       herokuish: v0.5.40
       buildpacks:
         heroku-buildpack-multi     v1.2.0
         heroku-buildpack-ruby      v244
         heroku-buildpack-nodejs    v202
         heroku-buildpack-clojure   v90
         heroku-buildpack-python    v223
         heroku-buildpack-java      v72
         heroku-buildpack-gradle    v38
         heroku-buildpack-scala     v96
         heroku-buildpack-play      v26
         heroku-buildpack-php       v227
         heroku-buildpack-go        v169
         heroku-buildpack-nginx     v22
         buildpack-null             v3
-----> dokku version: dokku version 0.28.4
-----> plugn version: plugn: 0.12.0build+3a27594
-----> dokku plugins: 
         00_dokku-standard    0.28.4 enabled    dokku core standard plugin
         20_events            0.28.4 enabled    dokku core events logging plugin
         app-json             0.28.4 enabled    dokku core app-json plugin
         apps                 0.28.4 enabled    dokku core apps plugin
         builder              0.28.4 enabled    dokku core builder plugin
         builder-dockerfile   0.28.4 enabled    dokku core builder-dockerfile plugin
         builder-herokuish    0.28.4 enabled    dokku core builder-herokuish plugin
         builder-lambda       0.28.4 enabled    dokku core builder-lambda plugin
         builder-null         0.28.4 enabled    dokku core builder-null plugin
         builder-pack         0.28.4 enabled    dokku core builder-pack plugin
         buildpacks           0.28.4 enabled    dokku core buildpacks plugin
         caddy-vhosts         0.28.4 enabled    dokku core caddy-vhosts plugin
         certs                0.28.4 enabled    dokku core certificate management plugin
         checks               0.28.4 enabled    dokku core checks plugin
         common               0.28.4 enabled    dokku core common plugin
         config               0.28.4 enabled    dokku core config plugin
         cron                 0.28.4 enabled    dokku core cron plugin
         docker-options       0.28.4 enabled    dokku core docker-options plugin
         domains              0.28.4 enabled    dokku core domains plugin
         enter                0.28.4 enabled    dokku core enter plugin
         git                  0.28.4 enabled    dokku core git plugin
         letsencrypt          0.13.0 enabled    Automated installation of let's encrypt TLS certificates
         logs                 0.28.4 enabled    dokku core logs plugin
         network              0.28.4 enabled    dokku core network plugin
         nginx-vhosts         0.28.4 enabled    dokku core nginx-vhosts plugin
         plugin               0.28.4 enabled    dokku core plugin plugin
         postgres             1.19.3 enabled    dokku postgres service plugin
         proxy                0.28.4 enabled    dokku core proxy plugin
         ps                   0.28.4 enabled    dokku core ps plugin
         redis                1.19.2 enabled    dokku redis service plugin
         registry             0.28.4 enabled    dokku core registry plugin
         repo                 0.28.4 enabled    dokku core repo plugin
         resource             0.28.4 enabled    dokku core resource plugin
         run                  0.28.4 enabled    dokku core run plugin
         scheduler            0.28.4 enabled    dokku core scheduler plugin
         scheduler-docker-local 0.28.4 enabled    dokku core scheduler-docker-local plugin
         scheduler-null       0.28.4 enabled    dokku core scheduler-null plugin
         shell                0.28.4 enabled    dokku core shell plugin
         ssh-keys             0.28.4 enabled    dokku core ssh-keys plugin
         storage              0.28.4 enabled    dokku core storage plugin
         trace                0.28.4 enabled    dokku core trace plugin
         traefik-vhosts       0.28.4 enabled    dokku core traefik-vhosts plugin
=====> qdon app-json information
       App json computed selected:    app.json
       App json global selected:      app.json
       App json selected:             
=====> qdon app information
       App created at:                1670488255
       App deploy source:             qdon
       App deploy source metadata:    qdon
       App dir:                       /home/dokku/qdon
       App locked:                    false
=====> qdon builder information
       Builder build dir:             
       Builder computed build dir:    
       Builder computed selected:     
       Builder global build dir:      
       Builder global selected:       
       Builder selected:              
=====> qdon builder-dockerfile information
       Builder dockerfile computed dockerfile path: Dockerfile               
       Builder dockerfile global dockerfile path: Dockerfile               
       Builder dockerfile dockerfile path:                          
=====> qdon builder-lambda information
       Builder lambda computed lambdayml path: lambda.yml               
       Builder lambda global lambdayml path: lambda.yml               
       Builder lambda lambdayml path:                          
=====> qdon builder-pack information
       Builder pack computed projecttoml path: project.toml             
       Builder pack global projecttoml path: project.toml             
       Builder pack projecttoml path:                          
=====> qdon buildpacks information
       Buildpacks computed stack:     gliderlabs/herokuish:latest-20
       Buildpacks global stack:       
       Buildpacks list:               
       Buildpacks stack:              
=====> qdon ssl information
       Ssl dir:                       /home/dokku/qdon/tls     
       Ssl enabled:                   true                     
       Ssl hostnames:                 qdon.space               
       Ssl expires at:                Mar  5 14:00:10 2023 GMT 
       Ssl issuer:                    C = US, O = Let's Encrypt, CN = R3
       Ssl starts at:                 Dec  5 14:00:11 2022 GMT 
       Ssl subject:                   subject=CN = qdon.space  
       Ssl verified:                  self signed              
=====> qdon checks information
       Checks disabled list:          none                     
       Checks skipped list:           none                     
=====> qdon cron information
       Cron task count:               3
=====> qdon docker options information
       Docker options build:          --link dokku.redis.qdon:dokku-redis-qdon 
       Docker options deploy:         --add-host es.qdon.space:10.25.96.4 --link dokku.redis.qdon:dokku-redis-qdon --restart=on-failure:10 
       Docker options run:            --add-host es.qdon.space:10.25.96.4 --link dokku.redis.qdon:dokku-redis-qdon 
=====> qdon domains information
       Domains app enabled:           true                     
       Domains app vhosts:            qdon.space               
       Domains global enabled:        true                     
       Domains global vhosts:         qdon.space               
=====> qdon git information
       Git deploy branch:             master                   
       Git global deploy branch:      master                   
       Git keep git dir:              false                    
       Git rev env var:               GIT_REV                  
       Git sha:                       2887900                  
       Git last updated at:           1667374746               
=====> qdon logs information
       Logs computed max size:        10m
       Logs global max size:          10m
       Logs global vector sink:       
       Logs max size:                 
       Logs vector sink:              
=====> qdon network information
       Network attach post create:           
       Network attach post deploy:           
       Network bind all interfaces:          false
       Network computed attach post create:  
       Network computed attach post deploy:  
       Network computed bind all interfaces: false
       Network computed initial network:     
       Network computed tld:                 
       Network global attach post create:    
       Network global attach post deploy:    
       Network global bind all interfaces:   false
       Network global initial network:       
       Network global tld:                   
       Network initial network:              
       Network static web listener:          
       Network tld:                          
       Network web listeners:                172.17.0.4:3000
=====> qdon nginx information
       Nginx access log format:                                
       Nginx access log path:         /var/log/nginx/qdon-access.log
       Nginx bind address ipv4:                                
       Nginx bind address ipv6:       ::                       
       Nginx client max body size:                             
       Nginx disable custom config:   false                    
       Nginx error log path:          /var/log/nginx/qdon-error.log
       Nginx global hsts:             true                     
       Nginx computed hsts:           true                     
       Nginx hsts:                                             
       Nginx hsts include subdomains: true                     
       Nginx hsts max age:            15724800                 
       Nginx hsts preload:            false                    
       Nginx proxy buffer size:       4096                     
       Nginx proxy buffering:         on                       
       Nginx proxy buffers:           8 4096                   
       Nginx proxy busy buffers size: 8192                     
       Nginx proxy read timeout:      60s                      
       Nginx last visited at:         1670490145               
       Nginx x forwarded for value:   $remote_addr             
       Nginx x forwarded port value:  $server_port             
       Nginx x forwarded proto value: $scheme                  
       Nginx x forwarded ssl:                                  
=====> qdon proxy information
       Proxy enabled:                 true
       Proxy port map:                http:80:3000 https:443:3000
       Proxy type:                    nginx
=====> qdon ps information
       Deployed:                      true
       Processes:                     3
       Ps can scale:                  true
       Ps computed procfile path:     Procfile
       Ps global procfile path:       Procfile
       Ps procfile path:              
       Ps restart policy:             on-failure:10
       Restore:                       true
       Running:                       true
       Status streaming 1:            running (CID: 60ef77c05e8)
       Status web 1:                  running (CID: ff54ff94dfc)
       Status worker 1:               running (CID: 9ee02a6b329)
=====> qdon registry information
       Registry computed image repo:      dokku/qdon
       Registry computed push on release: false
       Registry computed server:          
       Registry global push on release:   
       Registry global server:            
       Registry image repo:               
       Registry push on release:          
       Registry server:                   
       Registry tag version:              
=====> qdon resource information
=====> qdon scheduler information
       Scheduler computed selected:   docker-local
       Scheduler global selected:     docker-local
       Scheduler selected:            
=====> qdon scheduler-docker-local information
       Scheduler docker local disable chown:                          
       Scheduler docker local init process: true                     
       Scheduler docker local parallel schedule count:                          
=====> qdon storage information
       Storage build mounts:                                   
       Storage deploy mounts:                                  
       Storage run mounts:
```

**Comment by dominiceden** [comment]
I too had issues with upgrading to 0.29 and it not recognising my existing `nginx.conf.sigil` file at the root of my repo, therefore Cloudflare was showing a 521 error as it could not connect to my server. I could tell because 0.29.0's deploy output did not mention using the `nginx.conf.sigil` file but 0.28.0's deploy output prints out:
`-----> Overriding default nginx.conf with detected nginx.conf.sigil` 

I had to rollback to 0.28.0 with `apt-get install dokku=0.28.0` and it worked again instantly. I'm not sure what happened in 0.29.0 but something isn't working with how it handles `nginx.conf.sigil` files.

Also I don't really understand what _"The nginx.conf.sigil is now extracted when source code is extracted for a build and not from the built image."_ means.

**Comment by josegonzalez** [comment]
The file _should_ be pulled from the source image, but it wasn't for whatever reason. I've fixed this and updated the docs to reflect how this will work for `nginx.conf.sigil` and `Procfile`.

Both files should be fetched from the pushed code repository root - respecting the specified path overrides - and for image-based deploys, they will be fetched from the source image. I've also added a test case for this.

Closing as there is a pull request open. I'll get this merged in asap and likely make a release today/tomorrow.

**Comment by tribela** [comment]
this is not fixed on 0.29.1 and please link the pr and don't close until fixed.

**Comment by josegonzalez** [comment]
Do you have exact reproduction steps for what you are seeing? The linked PR even has a unit test for what I expect to happen. Without exact steps to reproduce and a test case that shows how it should work, I'm not sure what you want me to fix.
