### ISSUE TITLE
Dokku on Docker: services symlink issues again

### ISSUE THREAD

**Issue by maciejopalinski** [dokku/dokku#5614]
Plugin installs are failing, with following errors:

`dokku plugin:install https://github.com/dokku/dokku-redis.git redis`
```
mkdir: cannot create directory ‘/var/lib/dokku/services’: File exists
Failed to create Redis data directory
chown: cannot access '/var/lib/dokku/services/redis': No such file or directory
```

`dokku plugin:install https://github.com/dokku/dokku-postgres.git postgres`
```
mkdir: cannot create directory ‘/var/lib/dokku/services’: File exists
Failed to create Postgres data directory
chown: cannot access '/var/lib/dokku/services/postgres': No such file or directory
```

I build the dokku docker image myself, from latest commit: 0bbdee4c2bf8c96320b1edd723d74fcf009cb303

At the moment nothing works...

I think it is related to #5468 and #5606.
@josegonzalez

**Comment by josegonzalez** [comment]
Can you give me the exact steps you performed so I can replicate this issue?

**Comment by maciejopalinski** [comment]
> Can you give me the exact steps you performed so I can replicate this issue?

I just built the docker image locally from the latest commit.
I made sure that `/var/lib/dokku` does not exist on my host machine using: `rm -rf /var/lib/dokku`.

Then I started the docker container with the following command:
```
docker run --rm -it --env DOKKU_HOSTNAME=example.com --env DOKKU_HOST_ROOT=/var/lib/dokku/home/dokku --name dokku -p 3022:22 -p 8080:80 -p 8443:443 -v /var/lib/dokku:/mnt/dokku -v /var/run/docker.sock:/var/run/docker.sock my-dokku-build:latest
```

Then I opened a shell to the container using the command:
```
docker exec -it dokku bash
```

And finally executed the two commands to install plugins.

**Comment by maciejopalinski** [comment]
Dokku version is: `1674949226:0.29.4build+0bbdee4c`

**Comment by maciejopalinski** [comment]
I built the image with the following commands:
`./contrib/release-dokku build`
this command built the .deb packages for three architectures, but failed with some docker error (running it again right now to provide you with a log)

`docker build . -t my-dokku-build`

**Comment by maciejopalinski** [comment]
One thing to notice, that I find weird, is that when I look at the directory structure of `/var/lib/dokku` at THE HOST system, I see that there is `/var/lib/dokku` inside `/var/lib/dokku` (`/var/lib/dokku/var/lib/dokku`) and it contains some files. Take a look for yourself:
```
$ tree /var/lib/dokku
/var/lib/dokku/
├── etc
│   ├── nginx
│   │   └── dhparam.pem
│   └── ssh
│       ├── moduli
│       ├── ssh_config
│       ├── ssh_config.d
│       ├── sshd_config
│       ├── sshd_config.d
│       ├── ssh_host_ecdsa_key
│       ├── ssh_host_ecdsa_key.pub
│       ├── ssh_host_ed25519_key
│       ├── ssh_host_ed25519_key.pub
│       ├── ssh_host_rsa_key
│       └── ssh_host_rsa_key.pub
├── home
│   └── dokku
│       └── VHOST
└── var
    └── lib
        └── dokku
            ├── config
            │   ├── app-json
            │   ├── apps
            │   ├── builder
            │   ├── builder-dockerfile
            │   ├── builder-herokuish
            │   ├── builder-lambda
            │   ├── builder-pack
            │   ├── buildpacks
            │   ├── caddy
            │   │   └── --global
            │   │       └── proxy-status
            │   ├── checks
            │   ├── common
            │   ├── git
            │   ├── logs
            │   ├── network
            │   ├── nginx
            │   │   └── --global
            │   │       ├── nginx-conf-sigil-migrated
            │   │       └── proxy-status
            │   ├── ps
            │   ├── registry
            │   ├── resource
            │   ├── scheduler
            │   ├── scheduler-docker-local
            │   └── traefik
            │       └── --global
            │           └── proxy-status
            └── data
                ├── app-json
                ├── builder-lambda
                ├── caddy
                ├── git
                ├── logs
                ├── nginx-vhosts
                │   └── dokku-errors
                │       ├── 400-error.html
                │       ├── 404-error.html
                │       ├── 500-error.html
                │       └── 502-error.html
                ├── ps
                ├── scheduler-docker-local
                ├── storage
                └── traefik
                    └── traefik-acme.json

47 directories, 20 files
```

This is the state just after running the container and letting it generate its keys and stuff, no plugins, no nothing.

**Comment by maciejopalinski** [comment]
@josegonzalez any updates on this?

**Comment by maciejopalinski** [comment]
i would love to help, because i really admire your work

**Comment by josegonzalez** [comment]
Can you run:

```
dokku --trace plugin:install https://github.com/dokku/dokku-postgres.git postgres
```

In your built image?

**Comment by maciejopalinski** [comment]
> Can you run:
> 
> ```
> dokku --trace plugin:install https://github.com/dokku/dokku-postgres.git postgres
> ```
> 
> In your built image?

Yeah, here is the log: [install.log](https://github.com/dokku/dokku/files/10756749/install.log)

**Comment by josegonzalez** [comment]
What architecture/os are you building the base image on? We build that for several archs (armhf, arm64, amd64) in CI, so it should work fine locally....

**Comment by maciejopalinski** [comment]
> What architecture/os are you building the base image on? We build that for several archs (armhf, arm64, amd64) in CI, so it should work fine locally....

I tried it on `amd64`, but even the [image from Docker Hub](https://hub.docker.com/r/dokku/dokku) throws the same error. Tried running it on 3 separate machines. Did you reproduce the error?

**Comment by josegonzalez** [comment]
Okay I found the issue - was testing an image locally in a dir that already had the `services` directory created. Once I fixed this in the code, it seems to work. Patch incoming.

**Comment by josegonzalez** [comment]
You should be able to patch this by running the following within a running dokku container:

```shell
mkdir -p /mnt/dokku/var/lib/dokku/services
find "/var/lib/dokku/services" -print0 | xargs -0 chown -h dokku:dokku
```

Closing as there is a pull request open.

**Comment by maciejopalinski** [comment]
@josegonzalez is it related to [dokku-redis #185](https://github.com/dokku/dokku-redis/issues/185)? I thought it was related but issue still persists. Dokku is unusable in this state...

**Comment by maciejopalinski** [comment]
I mean all the directory structures are different, there is a lot of files missing, but those directories should be mounted and mirrored, i guess?

Here is the example that might help you understand:
```
$ find /var/lib/dokku/services/postgres/postgres-test/ -maxdepth 1
/var/lib/dokku/services/postgres/postgres-test/
/var/lib/dokku/services/postgres/postgres-test/data

$ docker exec dokku find /var/lib/dokku/services/postgres/postgres-test/ -maxdepth 1
/var/lib/dokku/services/postgres/postgres-test/
/var/lib/dokku/services/postgres/postgres-test/data
/var/lib/dokku/services/postgres/postgres-test/IMAGE
/var/lib/dokku/services/postgres/postgres-test/ENV
/var/lib/dokku/services/postgres/postgres-test/ID
/var/lib/dokku/services/postgres/postgres-test/LINKS
/var/lib/dokku/services/postgres/postgres-test/IMAGE_VERSION
/var/lib/dokku/services/postgres/postgres-test/PASSWORD
/var/lib/dokku/services/postgres/postgres-test/DATABASE_NAME
/var/lib/dokku/services/postgres/postgres-test/CONFIG_OPTIONS

$ docker exec dokku find /mnt/dokku/services/postgres/postgres-test/ -maxdepth 1
/mnt/dokku/services/postgres/postgres-test/
/mnt/dokku/services/postgres/postgres-test/data
```

What's wrong?
